/**
 * DS Health — consistency inventory for the design system.
 *
 * Everything here is generated by scripts/generate-ds-health.cjs from the same
 * audit that CI and .husky/pre-push run, so this page can never disagree with
 * what actually blocks a push.
 *
 * The list is not the point — `npm run audit:tokens` already prints it. The
 * point is the VERDICT column. A finding with no recorded decision gets
 * re-litigated every time someone new sees it: the local `Stepper` that turned
 * out to be a numeric input, not a shadow of the DS wizard `Stepper`, was
 * correctly left alone, and without a written record the next person asks the
 * same question. Verdicts are recorded by hand in ds-decisions.json.
 *
 * Repeats are the other signal. The same hand-rolled name in three screens is
 * not three mistakes — it is one missing DS component with demand behind it.
 */

import { CardContainer } from "@/components/ui/card-container"
import { Table, type TableColumn } from "@/components/ui/table"
import { Tag, type TagVariant } from "@/components/ui/tag"
import { EmptyState } from "@/components/ui/empty-state"
import { AlertBanner } from "@/components/ui/alert-banner"
import health from "@/ds-health.json"
import dsIndex from "@/../ds-index.json"

type Verdict = "align" | "promote" | "accepted" | "undecided"

type Finding = {
  key:         string
  type:        string
  typeLabel:   string
  file:        string
  line:        number | null
  name:        string | null
  count:       number | null
  lines:       number[] | null
  message:     string
  verdict:     Verdict
  why:         string | null
  decidedBy:   string | null
  decidedOn:   string | null
  repeatCount?: number
}

const VERDICT: Record<Verdict, { label: string; tag: TagVariant; help: string }> = {
  undecided: {
    label: "Undecided",
    tag:   "alert",
    help:  "Nobody has ruled on this yet. Every finding should end up in one of the other three.",
  },
  align: {
    label: "Align",
    tag:   "informative",
    help:  "The DS already covers this — the screen should use the real component.",
  },
  promote: {
    label: "Promote",
    tag:   "purple",
    help:  "A genuine gap. Becomes a new DS component, or a variant of an existing one.",
  },
  accepted: {
    label: "Accepted",
    tag:   "neutral",
    help:  "A false positive or a deliberate exception. It stays as it is.",
  },
}

const findings = health.findings as Finding[]
const totals   = health.totals as Record<string, number>
const legend   = health.legend as Record<string, { label: string; blurb: string }>
const stale    = (health.staleDecisions ?? []) as string[]

function Stat({ label, value, hint }: { label: string; value: number | string; hint?: string }) {
  return (
    <CardContainer variant="default" size="default">
      <div style={{ fontSize: 24, fontWeight: 700, lineHeight: 1, color: "var(--color-text-title)" }}>{value}</div>
      <div style={{ fontSize: 12, color: "var(--color-text-subtitle)", marginTop: 6 }}>{label}</div>
      {hint && (
        <div style={{ fontSize: 11, color: "var(--muted-foreground)", marginTop: 4, lineHeight: 1.4 }}>{hint}</div>
      )}
    </CardContainer>
  )
}

export function DsHealthPage() {
  const undecided = totals.undecided ?? 0
  const promotable = (dsIndex as { promotionQueue?: { id: string; usedInScreens: number; import: string }[] })
    .promotionQueue ?? []

  const columns: TableColumn<Finding>[] = [
    {
      key: "verdict",
      header: "Verdict",
      width: "130px",
      render: (f) => (
        <Tag variant={VERDICT[f.verdict].tag} size="sm">
          {VERDICT[f.verdict].label}
        </Tag>
      ),
    },
    {
      key: "what",
      header: "What",
      render: (f) => (
        <div>
          <div style={{ fontSize: 13, fontWeight: 600, color: "var(--foreground)" }}>
            {f.name ?? f.typeLabel}
          </div>
          <div style={{ fontSize: 11, color: "var(--muted-foreground)", marginTop: 2 }}>{f.typeLabel}</div>
        </div>
      ),
    },
    {
      key: "where",
      header: "Where",
      render: (f) => (
        <div style={{ fontSize: 12, color: "var(--color-text-subtitle)", fontFamily: "ui-monospace, monospace" }}>
          {f.file.replace("src/", "")}
          {f.lines ? `:${f.lines.join(", ")}` : f.line ? `:${f.line}` : ""}
        </div>
      ),
    },
    {
      key: "repeat",
      header: "Repeats",
      width: "80px",
      align: "center",
      render: (f) =>
        f.repeatCount && f.repeatCount > 1 ? (
          // 3+ of the same name is the threshold where this stops being a
          // mistake and starts being a missing component with demand behind it.
          <Tag variant={f.repeatCount >= 3 ? "purple" : "secondary"} size="sm">
            ×{f.repeatCount}
          </Tag>
        ) : (
          <span style={{ fontSize: 12, color: "var(--muted-foreground)" }}>—</span>
        ),
    },
    {
      key: "why",
      header: "Why",
      render: (f) =>
        f.why ? (
          <div style={{ fontSize: 12, color: "var(--color-text-subtitle)", lineHeight: 1.45 }}>
            {f.why}
            {f.decidedBy && (
              <span style={{ color: "var(--muted-foreground)" }}>
                {" "}— {f.decidedBy}, {f.decidedOn}
              </span>
            )}
          </div>
        ) : (
          <span style={{ fontSize: 12, color: "var(--muted-foreground)" }}>—</span>
        ),
    },
  ]

  return (
    <div className="flex flex-col gap-[24px]">
      <div>
        <h1 style={{ fontSize: 24, fontWeight: 600, color: "var(--color-text-title)" }}>DS Health</h1>
        <p style={{ fontSize: 14, color: "var(--color-text-subtitle)", marginTop: 4, maxWidth: 720, lineHeight: 1.5 }}>
          Every place a screen builds something the design system already covers — plus what we decided about it.
          Generated from the same audit that runs in CI and before every push, so it can never drift from what
          actually blocks a merge.
        </p>
      </div>

      {stale.length > 0 && (
        <AlertBanner
          state="alert"
          title={`${stale.length} recorded decision(s) no longer match any finding`}
          description={`Someone fixed them, or the file was renamed. Prune them from ds-decisions.json so it does not rot the way specs/ did: ${stale.join(", ")}`}
        />
      )}

      {/* Grid rather than flex-wrap: with 5 tiles the last one would wrap alone
          and stretch to the full row width. */}
      <div className="grid gap-[12px] grid-cols-2 md:grid-cols-3 lg:grid-cols-5">
        <Stat label="Open findings" value={findings.length} />
        <Stat label="Undecided" value={undecided} hint={undecided === 0 ? "Nothing waiting on a call" : "Waiting on your call"} />
        <Stat label="To align" value={totals.align ?? 0} hint="Use the real DS component" />
        <Stat label="To promote" value={totals.promote ?? 0} hint="Candidates for a component or variant" />
        <Stat label="Accepted" value={totals.accepted ?? 0} hint="False positives and exceptions" />
          <Stat label="Ready to promote" value={promotable.length} hint="Candidates used in 2+ screens" />
      </div>

        {/* ── Promotion queue ──────────────────────────────────────────────
            Candidates used in two or more screens. Two is the line because one
            use is a single screen's decision and two is a pattern — and a
            pattern belongs in the catalog with a spec behind it.

            This counts imports, not copies. The duplicate-component finding
            above catches the same component written twice, which is the failure
            this queue exists to prevent; once reuse works that check goes quiet
            and a candidate imported by five screens would never surface here. */}
        {promotable.length > 0 && (
          <div className="flex flex-col gap-[10px]">
            <div style={{ fontSize: 14, fontWeight: 600, color: "var(--foreground)" }}>
              Ready to promote
            </div>
            <p style={{ fontSize: 13, color: "var(--color-text-subtitle)", lineHeight: 1.6, margin: 0, maxWidth: "68ch" }}>
              Built for one prototype, now used in more than one. Give it a spec — size class, widths,
              states, dontUse — and move it from experimental/ to ui/.
            </p>
            <CardContainer size="sm" className="!p-0 overflow-hidden">
              <Table
                size="sm"
                columns={[
                  { key: "id",   header: "Candidate", width: "30%" },
                  { key: "uses", header: "Used in",   width: "20%" },
                  { key: "path", header: "Import",    width: "50%" },
                ] as TableColumn<{ id: string; uses: string; path: string }>[]}
                data={promotable.map((c) => ({
                  id:   c.id,
                  uses: `${c.usedInScreens} screens`,
                  path: c.import,
                }))}
              />
            </CardContainer>
          </div>
        )}

      {findings.length === 0 ? (
        <EmptyState
          title="No open inconsistencies"
          description="No screen is rebuilding something the DS already covers. The ratchet stops this number rising, so it holds unless someone bypasses it deliberately."
        />
      ) : (
        <CardContainer size="sm" className="!p-0 overflow-hidden">
          <Table columns={columns} data={findings} size="sm" />
        </CardContainer>
      )}

      <CardContainer variant="default" size="default">
        <div style={{ fontSize: 14, fontWeight: 600, color: "var(--foreground)", marginBottom: 8 }}>
          How a verdict gets recorded
        </div>
        <p style={{ fontSize: 13, color: "var(--color-text-subtitle)", lineHeight: 1.6, marginBottom: 12 }}>
          Findings generate themselves; verdicts are written by hand in <code>ds-decisions.json</code>, keyed by the
          value shown in this table. Then run <code>npm run generate:ds-health</code> and the page catches up. Every
          verdict needs a <em>why</em> — a ruling with no reasoning is how the next person ends up reversing a
          decision that was right.
        </p>
        <div className="flex flex-col gap-[8px]">
          {(Object.keys(VERDICT) as Verdict[]).filter((v) => v !== "undecided").map((v) => (
            <div key={v} className="flex items-start gap-[8px]">
              <Tag variant={VERDICT[v].tag} size="sm">{VERDICT[v].label}</Tag>
              <span style={{ fontSize: 12, color: "var(--color-text-subtitle)", lineHeight: 1.5 }}>
                {VERDICT[v].help}
              </span>
            </div>
          ))}
        </div>
      </CardContainer>

      <CardContainer variant="default" size="default">
        <div style={{ fontSize: 14, fontWeight: 600, color: "var(--foreground)", marginBottom: 8 }}>
          What each check looks at
        </div>
        <div className="flex flex-col gap-[10px]">
          {Object.entries(legend).map(([k, v]) => (
            <div key={k}>
              <div style={{ fontSize: 13, fontWeight: 600, color: "var(--foreground)" }}>{v.label}</div>
              <div style={{ fontSize: 12, color: "var(--color-text-subtitle)", lineHeight: 1.5, marginTop: 2 }}>
                {v.blurb}
              </div>
            </div>
          ))}
        </div>
      </CardContainer>
    </div>
  )
}
